config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  get 'quizs/index'

  resources :users, only: [:show]
  resources :tweets, only: [:index, :new, :create, :destroy, :edit, :update]
  resources :tweets do
    resource :favorites, only: [:create, :destroy]
  end
  resources :quizs do
    collection do
      get 'store_manager'
      get 'employee'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :tweet

  validates_uniqueness_of :tweet_id, scope: :user_id
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :text, presence: true
  belongs_to :user
  has_many :favorites, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :username, presence: true

  def already_favorited?(tweet)
    self.favorites.exists?(tweet_id: tweet.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @favorite = current_user.favorites.create(tweet_id: params[:tweet_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @tweet = Tweet.find(params[:tweet_id])
    @favorite = current_user.favorites.find_by(tweet_id: @tweet.id)
    @favorite.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end

end

app/controllers/quizs_controller.rb
class QuizsController < ApplicationController

  def index
    
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :move_to_index, except: [:index]

  def index
    @tweets = Tweet.includes(:user).order("created_at DESC")
  end

  def new
    @tweet = Tweet.new
  end

  def create
    Tweet.create(tweet_params)
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    tweet = Tweet.find(params[:id])
    tweet.update(tweet_params)
  end

  private
  def tweet_params
    params.require(:tweet).permit(:text).merge(user_id: current_user.id)
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    user = User.find(params[:id])
    @name = user.username
    @tweets = user.tweets
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  private
  def user_params
    params.require(:user).permit(:username, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/quiz_helper.rb
module QuizHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheets" href="style.css">
  <meta name="viewport" content="width=device-width">
</head>
<body>
  <div class="container">
    <div class="contents">
      <% if user_signed_in? %>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "button is-warning is-light" %>
        <%= link_to "マイページ", user_path(current_user) %>
        <%= link_to "ちょこっとボイス", tweets_path %>
      <% else %>
        <%= link_to "ログイン", new_user_session_path, class: "button is-warning is-light" %>
        <%= link_to "新規登録", new_user_registration_path, class: "button is-warning is-light" %>
     <% end %>
    </div>
    <div class="info">
      <p>【 お知らせ 】</p>
      <p>12/2 店長用問題を５問追加しました。</p>
      <p>11/29 社員用問題文を一部修正しました。</p>
    </div>
      <% if user_signed_in? %>
        <div class="content-quiz1">
          <button class="button-index"><%= link_to "店長", store_manager_quizs_path, class: 'tyr-btn', id:"try-btn-id" %></button>
          <button class="button-index"><%= link_to "社員", employee_quizs_path, class: "tyr-btn", id:"try-btn-id" %></button>
        </div>
        <div class="content-quiz2">
          <button class="button-index"><%= link_to "PA", store_manager_quizs_path, class: 'tyr-btn', id:"try-btn-id" %></button>
          <button class="button-index"><%= link_to "理念", employee_quizs_path, class: "tyr-btn", id:"try-btn-id" %></button>
        </div>
      <% end %>
    </div>
  </div>
</body>
<footer>
</footer>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HUNK Quiz</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar-brand">
      <%= link_to root_path, class: "navbar-item" do %>
        <h1 class="title is-4" style="font-family: cursive; font-size: 60px; display: flex; justify-content: center;">HUNK Quiz</h1>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/quizs/employee.html.erb
<!DOCTYPE HTML>
<html>
<head>
  <meta charset="utf-8">
</head>
<div class="container">
<script src='https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js?ver=1.12.4'></script>
<script>
$(function(){
    var quizArea = $('.quiz_area'); //クイズを管理するDOMを指定
    var quiz_html = quizArea.html(); //もう一度を押した時に元に戻すため初期HTMLを変数で保管
    var quiz_cnt = 0; //現在の問題数を管理
    var quiz_fin_cnt = 5; //何問で終了か設定（クイズ数以下であること）
    var quiz_success_cnt = 0; //問題の正解数
    
    //クイズの配列を設定
    //answerの選択肢の数はいくつでもOKただし先頭を正解とすること(出題時に選択肢はシャッフルされる)
    var aryQuiz = [];
    aryQuiz.push(
        {
            question : 'プロフェッショナルマインドの３番目は？',
            answer : ['プロフェッショナルな身だしなみに徹し、誇りをもつ', '丁寧かつスピーディーに行動する', 'お客様と感動を共有するブランドレストラン創り', 'カッティングはプロ意識を持つ']
        }
        ,{
            question : 'おもてなし４項目でないものは？',
            answer : ['ニコ・キビ・ハキ', '中間バッシング', 'お茶おしぼり交換', 'お見送り', '商品説明']
        }
        ,{
            question : '発注する時に気をつけることは？',
            answer : ['売上に合わせて発注する', '在庫切れを起こさないように多めに発注する', 'ロスを減らすため少なめに発注する', '毎日一定数の発注をする']
        }
        ,{
            question : '納品時に気をつけることで適切ではないものは？',
            answer : ['受領処理をしてから検品する', '片付ける前に検品する', '数量を確認する', '欠品があったので業者に確認する']
        }
        ,{
            question : 'キャストに楽しく働いてもらうために日々伝える大切なことは？',
            answer : ['理念', '作業の効率化', '楽しいおしゃべり', '社会の厳しさ']
        }
    );
    
    quizReset();
    
    //回答を選択した後の処理
    quizArea.on('click', '.quiz_ans_area ul li', function(){
        //画面を暗くするボックスを表示（上から重ねて、結果表示中は選択肢のクリックやタップを封じる
        quizArea.find('.quiz_area_bg').show();
        //選択した回答に色を付ける
        $(this).addClass('selected');
        if($(this).data('true')){
            //正解の処理 〇を表示
            quizArea.find('.quiz_area_icon').addClass('true');
            //正解数をカウント
            quiz_success_cnt++;
        }else{
            //不正解の処理
            quizArea.find('.quiz_area_icon').addClass('false');
        }
        setTimeout(function(){
            //表示を元に戻す
            quizArea.find('.quiz_ans_area ul li').removeClass('selected');
            quizArea.find('.quiz_area_icon').removeClass('true false');
            quizArea.find('.quiz_area_bg').hide();
            //問題のカウントを進める
            quiz_cnt++;
            if(quiz_fin_cnt > quiz_cnt){
                //次の問題を設定する
                quizShow();
            }else{
                //結果表示画面を表示
                quizResult();
            }
        }, 1500);
    });
    
    //もう一度挑戦するを押した時の処理
    quizArea.on('click', '.quiz_restart', function(){
        quizReset();
    });
    
    //リセットを行う関数
    function quizReset(){
        quizArea.html(quiz_html); //表示を元に戻す
        quiz_cnt = 0;
        quiz_success_cnt = 0;
        //aryQuiz = arrShuffle(aryQuiz); //毎回出題の順番をシャッフルしたい場合はここのコメントを消してね
        quizShow();
    }
    
    //問題を表示する関数
    function quizShow(){
        //何問目かを表示
        quizArea.find('.quiz_no').text((quiz_cnt + 1));
        //問題文を表示
        quizArea.find('.quiz_question').text(aryQuiz[quiz_cnt]['question']);
        //正解の回答を取得する
        var success = aryQuiz[quiz_cnt]['answer'][0];
        //現在の選択肢表示を削除する
        quizArea.find('.quiz_ans_area ul').empty();
        //問題文の選択肢をシャッフルさせる(自作関数) .concat()は参照渡し対策
        var aryHoge = arrShuffle(aryQuiz[quiz_cnt]['answer'].concat());
        //問題文の配列を繰り返し表示する
        $.each(aryHoge, function(key, value){
            var fuga = '<li>' + value + '</li>';
            //正解の場合はdata属性を付与する
            if(success === value){
                fuga = '<li data-true="1">' + value + '</li>';
            }
            quizArea.find('.quiz_ans_area ul').append(fuga);
        });
    }
    
    //結果を表示する関数
    function quizResult(){
        quizArea.find('.quiz_set').hide();
        var text = quiz_fin_cnt + '問中' + quiz_success_cnt + '問正解！';
        if(quiz_fin_cnt === quiz_success_cnt){
            text += '<br>全問正解おめでとう！';
        }
        text += '<br><input type="button" value="もう一度挑戦する" class="quiz_restart p-10">';
        quizArea.find('.quiz_result').html(text);
        quizArea.find('.quiz_result').show();
    }
    
    //配列をシャッフルする関数
    function arrShuffle(arr){
        for(i = arr.length - 1; i > 0; i--){
            var j = Math.floor(Math.random() * (i + 1));
            var tmp = arr[i];
            arr[i] = arr[j];
            arr[j] = tmp;
        }
        return arr;
    }
});
</script>
<body>
<div class="content">
  <h1>社員用クイズ 全５問</h1>
  <div class="quiz_area">
    <div class="quiz_set">
        第<span class="quiz_no">0</span>問
        <div class="quiz_question"></div>
        <div class="quiz_ans_area">
          <ul>
          </ul>
        </div>
        <div class="quiz_area_bg"></div>
        <div class="quiz_area_icon"></div>
    </div>
    <div class="quiz_result"></div>
  </div>
</div>
<div class="try_date"></div>
<%= link_to "ホームへ", root_path %>
<%= link_to "マイページへ", user_path(current_user) %>
<%= link_to "結果を共有しよう", tweets_path %>
</body>
</div>
</html>

app/views/quizs/store_manager.html.erb
<!DOCTYPE HTML>
<html>
<head>
  <meta charset="utf-8">
</head>
<script src='https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js?ver=1.12.4'></script>
<div class="container">
<script>
$(function(){
    var quizArea = $('.quiz_area'); //クイズを管理するDOMを指定
    var quiz_html = quizArea.html(); //もう一度を押した時に元に戻すため初期HTMLを変数で保管
    var quiz_cnt = 0; //現在の問題数を管理
    var quiz_fin_cnt = 5; //何問で終了か設定（クイズ数以下であること）
    var quiz_success_cnt = 0; //問題の正解数
    
    //クイズの配列を設定
    //answerの選択肢の数はいくつでもOKただし先頭を正解とすること(出題時に選択肢はシャッフルされる)
    var aryQuiz = [];
    aryQuiz.push(
        {
            question : '売上の構成は次のうちどれ？',
            answer : ['客数×客単価', '組数×客単価', '商品出数×客数', '客単価×組単価']
        }
        ,{
            question : '仕入れ原価とは次のうちどれ？',
            answer : ['今月仕入れた食材費', '今月使用した食材費', '先月の在庫から今月の在庫を引いた金額', '今月の実質原価と同じ金額']
        }
        ,{
            question : '今月売上予測7000。先月在庫500。中間棚卸し時、実質原価32％。在庫を550にしたい時の仕入れ金額はいくら？',
            answer : ['2290', '2390', '2240', '2930']
        }
        ,{
            question : '原価を良くする方法で適切なものは？',
            answer : ['原価のいい商品をお薦めする', '値引き商品をお薦めする', '単価の高い商品をお薦めする', '単価の低い商品をお薦めする']
        }
        ,{
            question : '売上8500のお店の人件費率を17％の目標にしたい。今月の人件費はいくら？',
            answer : ['社員800 PA645', '社員800 PA456', '社員900 PA654', '社員900 PA564']
        }
    );
    
    quizReset();
    
    //回答を選択した後の処理
    quizArea.on('click', '.quiz_ans_area ul li', function(){
        //画面を暗くするボックスを表示（上から重ねて、結果表示中は選択肢のクリックやタップを封じる
        quizArea.find('.quiz_area_bg').show();
        //選択した回答に色を付ける
        $(this).addClass('selected');
        if($(this).data('true')){
            //正解の処理 〇を表示
            quizArea.find('.quiz_area_icon').addClass('true');
            //正解数をカウント
            quiz_success_cnt++;
        }else{
            //不正解の処理
            quizArea.find('.quiz_area_icon').addClass('false');
        }
        setTimeout(function(){
            //表示を元に戻す
            quizArea.find('.quiz_ans_area ul li').removeClass('selected');
            quizArea.find('.quiz_area_icon').removeClass('true false');
            quizArea.find('.quiz_area_bg').hide();
            //問題のカウントを進める
            quiz_cnt++;
            if(quiz_fin_cnt > quiz_cnt){
                //次の問題を設定する
                quizShow();
            }else{
                //結果表示画面を表示
                quizResult();
            }
        }, 1500);
    });
    
    //もう一度挑戦するを押した時の処理
    quizArea.on('click', '.quiz_restart', function(){
        quizReset();
    });
    
    //リセットを行う関数
    function quizReset(){
        quizArea.html(quiz_html); //表示を元に戻す
        quiz_cnt = 0;
        quiz_success_cnt = 0;
        //aryQuiz = arrShuffle(aryQuiz); //毎回出題の順番をシャッフルしたい場合はここのコメントを消してね
        quizShow();
    }
    
    //問題を表示する関数
    function quizShow(){
        //何問目かを表示
        quizArea.find('.quiz_no').text((quiz_cnt + 1));
        //問題文を表示
        quizArea.find('.quiz_question').text(aryQuiz[quiz_cnt]['question']);
        //正解の回答を取得する
        var success = aryQuiz[quiz_cnt]['answer'][0];
        //現在の選択肢表示を削除する
        quizArea.find('.quiz_ans_area ul').empty();
        //問題文の選択肢をシャッフルさせる(自作関数) .concat()は参照渡し対策
        var aryHoge = arrShuffle(aryQuiz[quiz_cnt]['answer'].concat());
        //問題文の配列を繰り返し表示する
        $.each(aryHoge, function(key, value){
            var fuga = '<li>' + value + '</li>';
            //正解の場合はdata属性を付与する
            if(success === value){
                fuga = '<li data-true="1">' + value + '</li>';
            }
            quizArea.find('.quiz_ans_area ul').append(fuga);
        });
    }
    
    //結果を表示する関数
    function quizResult(){
        quizArea.find('.quiz_set').hide();
        var text = quiz_fin_cnt + '問中' + quiz_success_cnt + '問正解！';
        if(quiz_fin_cnt === quiz_success_cnt){
            text += '<br>全問正解おめでとう！';
        }
        text += '<br><input type="button" value="もう一度挑戦する" class="quiz_restart p-10">';
        quizArea.find('.quiz_result').html(text);
        quizArea.find('.quiz_result').show();
    }
    
    //配列をシャッフルする関数
    function arrShuffle(arr){
        for(i = arr.length - 1; i > 0; i--){
            var j = Math.floor(Math.random() * (i + 1));
            var tmp = arr[i];
            arr[i] = arr[j];
            arr[j] = tmp;
        }
        return arr;
    }
});
</script>
<body>
<div class="content">
  <h1>店長用クイズ 全５問</h1>
  <div class="quiz_area">
    <div class="quiz_set">
        第<span class="quiz_no">0</span>問
        <div class="quiz_question"></div>
        <div class="quiz_ans_area">
          <ul>
          </ul>
        </div>
        <div class="quiz_area_bg"></div>
        <div class="quiz_area_icon"></div>
    </div>
    <div class="quiz_result"></div>
  </div>
</div>
<div class="try_date"></div>
<%= link_to "ホームへ", root_path %>
<%= link_to "マイページへ", user_path(current_user) %>
<%= link_to "結果を共有しよう", tweets_path %>
</body>
</div>
</html>

app/views/tweets/create.html.erb
<div class="contents">
  <div class="success">
    <h3>投稿が完了しました。</h3>
    <button class="button-tyr"><a class="btn" href="/">ホームへ戻る</a></button>
  </div>
</div>

app/views/tweets/destroy.html.erb
<div class="contents">
  <div class="success">
    <h3>削除が完了しました。</h3>
    <button class="button-tyr"><a class="btn" href="/">ホームへ戻る</a></button>
  </div>
</div>

app/views/tweets/edit.html.erb
<div class="container">
<div class="contents row">
<h3 >内容編集</h3>
  <div class="command">
    <%= form_with(model: @tweet, local: true) do |form| %>
      <%= form.text_area :text, placeholder: "書いたら更新ボタンを押してね", rows: "7", cols: "40" %>
      <%= form.submit "更新" %>
    <% end %>
  </div>
</div>
</div>

app/views/tweets/index.html.erb
<div class="container">
  <h1>みんなのちょこっとボイス</h1>
  <button class="button-tyr"><a class="tyr-btn" href="/tweets/new">投稿する</a></button>
    <div class="contents row">
      <% @tweets.each do |tweet| %>
      <div class="group">
        <p><%= tweet.text %></p>
        <a href="/users/<%= tweet.user.id %>">
         <%= tweet.user.username %><a>さんの投稿</a>
        </a>
        <% if current_user.already_favorited?(tweet) %>
          <%= link_to "いいねを外す", tweet_favorites_path(tweet), method: :delete %>
          <%= tweet.favorites.count %>
        <% else %>
          <%= link_to "いいね", tweet_favorites_path(tweet), method: :post %>
          <%= tweet.favorites.count %>
        <% end %>
        <%= tweet.created_at %>
      </div>
      <% end %>
    </div>
</div>

app/views/tweets/new.html.erb
<div class="contents row">
  <div class="container">
    <h3>結果を共有してみよう</h3>
    <div class="command">
    <%= form_with(model: @tweet, local: true) do |form| %>
      <%= form.text_area :text, placeholder: "何でも書いてみよう", rows: "10", cols: "40" %>
      <%= form.submit "投稿する" %>
    <% end %>
    </div>
  </div>
</div>

app/views/tweets/update.html.erb
<div class="contents">
  <div class="success">
    <h3>更新が完了しました。</h3>
    <button class="button-tyr"><a class="btn" href="/">ホームへ戻る</a></button>
  </div>
</div>

app/views/users/edit.html.erb
<h1>編集ページ</h1>
<p>名前とメールアドレスを変更できるよ</p>
<%= form_for @user do |f| %>

  <%= f.label :username %>
  <%= f.text_field :username %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.submit "更新" %>
<% end %>

app/views/users/index.html.erb
<% @users.each do |user| %>
<%= user.username %>
<% end %>

app/views/users/show.html.erb
<h1>マイページ</h1>
<div class="container">
  <p><%= @name %>さんの投稿一覧</p>
  <% @tweets.each do |tweet| %>
  <div class="group">
    <p><%= tweet.text %></p>
    <% if user_signed_in? && current_user.id == tweet.user_id %>
      <%= link_to '削除', tweet_path(tweet.id), method: :delete %>
      <%= link_to '編集', edit_tweet_path(tweet.id), method: :get %>
    <% end %>
    <a>いいね  </a><%= tweet.favorites.count %>
    <%= tweet.created_at %>
  </div>
  <% end %>
</div>